title: Nothing yet
email: samousavih@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  If you cannot explain something in simple terms, you don't understand it.(Feynman)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amin_mousavih
github_username:  samousavih

# Build settings
theme: minima
plugins:
  - jekyll-feed
